/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rohan Joshi
 */
public class ISSUE_RECORD1 extends javax.swing.JFrame {

    /**
     * Creates new form ISSUE_RECORD
     */
    public ISSUE_RECORD1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        year2 = new javax.swing.JComboBox<>();
        month2 = new javax.swing.JComboBox<>();
        day2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        UPDATE = new javax.swing.JButton();
        ENABLE_EDIT_TO_UPDATE = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ADD_RECORD = new javax.swing.JButton();
        ENABLE_EDIT_TO_ADD = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        HOME = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        SEARCH_BID = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        CLEAR = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        prn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        issued = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        issuedate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ISSUE_DATE");

        year.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "2020", "2021", "2022", "2023", "2024" }));
        year.setEnabled(false);

        month.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        month.setEnabled(false);

        day.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAY", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("RETURN_DATE");

        year2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        year2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "2020", "2021", "2022", "2023", "2024" }));
        year2.setEnabled(false);

        month2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        month2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        month2.setEnabled(false);

        day2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        day2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAY", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day2.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(month, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yes.setText("YES");
        yes.setEnabled(false);

        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        no.setText("NO");
        no.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("ISSUED");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no)
                            .addComponent(yes)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(no)
                .addContainerGap())
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        ENABLE_EDIT_TO_UPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ENABLE_EDIT_TO_UPDATE.setText("ENABLE EDITING TO UPDATE");
        ENABLE_EDIT_TO_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENABLE_EDIT_TO_UPDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ENABLE_EDIT_TO_UPDATE)
                    .addComponent(UPDATE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ENABLE_EDIT_TO_UPDATE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UPDATE)
                .addGap(18, 18, 18))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        ADD_RECORD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADD_RECORD.setText("ADD_RECORD");
        ADD_RECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_RECORDActionPerformed(evt);
            }
        });

        ENABLE_EDIT_TO_ADD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ENABLE_EDIT_TO_ADD.setText("ENABLE EDITING TO ADD");
        ENABLE_EDIT_TO_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENABLE_EDIT_TO_ADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADD_RECORD)
                    .addComponent(ENABLE_EDIT_TO_ADD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ENABLE_EDIT_TO_ADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADD_RECORD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        HOME.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HOME.setText("HOME");
        HOME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(HOME, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(HOME)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("BOOK_ID");

        SEARCH_BID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SEARCH_BID.setText("SEARCH");
        SEARCH_BID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BIDActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SEARCH TRANSACTION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(SEARCH_BID))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SEARCH_BID)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("BOOK_NAME");

        bname.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("AUTHOR");

        author.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CATEGORY");

        category.setEditable(false);
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("PRICE");

        price.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bname, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(author)
                    .addComponent(category)
                    .addComponent(price))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        CLEAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLEAR)
                    .addComponent(EXIT))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CLEAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("REGISTRATION_NO");

        prn.setEditable(false);
        prn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NAME");

        name.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ISSUED");

        issued.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ISSUE_DATE");

        issuedate.setEditable(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(prn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(issued, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(issuedate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(issued, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(prn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(issued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prnActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void SEARCH_BIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BIDActionPerformed
        // TODO add your handling code here:
       //int a=Integer.parseInt(bid.getText());
      /* int p=Integer.parseInt(prn.getText());
        try{
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
            
            //String query1="select*from addbook where book_id="+a+" and issued='yes';";
 //String query1="select*from addbook,return_book where addbook.book_id and return_book.book_id="+a+" and issued='yes';";
String query1="select*from addbook,return_book where addbook.book_id =return_book.book_id and registration_no="+p+" and issued='yes';";
//String query1="selectfrom addbook,return_book where addbook.book_id,return_book.book_id="+a+" and issued='yes';";
            
            ResultSet rs=stmt.executeQuery(query1);
           
            /*String BNAME="",AUTHOR="",CATEGORY="",NAME="",ISSUED="",ISSUE_DATE;
            int BID=0,PRN=0;
            while(rs.next()){
                BID=rs.getInt("book_id");
                BNAME=rs.getString("book_name");
                AUTHOR=rs.getString("author");
                CATEGORY=rs.getString("category");
                NAME=rs.getString("name");
                ISSUED=rs.getString("issued");
                ISSUE_DATE=rs.getString("issue_date");
                PRN=rs.getInt("registration_no");
              */  
                
                
             /*   String BNAME="",AUTHOR="",CATEGORY="",NAME="",ISSUED="",ISSUE_DATE;
            int BID=0,PRN=0;
            while(rs.next()){
                BID=rs.getInt("book_id");
                BNAME=rs.getString("book_name");
                AUTHOR=rs.getString("author");
                CATEGORY=rs.getString("category");
                NAME=rs.getString("name");
                ISSUED=rs.getString("issued");
                ISSUE_DATE=rs.getString("issue_date");
                PRN=rs.getInt("registration_no");
                
                
                bid.setText(Integer.toString(BID));
                bname.setText(BNAME);
                author.setText(AUTHOR);
                category.setText(CATEGORY);
                name.setText(NAME);
                issued.setText(ISSUED);
                issuedate.setText(ISSUE_DATE);
                prn.setText(Integer.toString(PRN));
               
         bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(true);
        name.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"error");
        }*/
            
            //String query2="select*from return_book where book_id="+a+";";
            int a=Integer.parseInt(bid.getText());
          try{
              
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
             
            String query2="select*from addbook where book_id="+a+";";
             Statement stmt1=con.createStatement();
              ResultSet rs1=stmt1.executeQuery(query2);
             String BNAME1="",AUTHOR1="",CATEGORY1="",ISSUED1="";
            int BID1=0,PRICE; 
            while(rs1.next()){
                BID1=rs1.getInt("book_id");
                BNAME1=rs1.getString("book_name");
                AUTHOR1=rs1.getString("author");
                CATEGORY1=rs1.getString("category");
                 PRICE=rs1.getInt("price");
                
                bid.setText(Integer.toString(BID1));
                 price.setText(Integer.toString(PRICE));
                bname.setText(BNAME1);
                author.setText(AUTHOR1);
                category.setText(CATEGORY1);
                author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        price.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false);
                
            }
              
        }
        catch(Exception err){
            JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_SEARCH_BIDActionPerformed

    private void ADD_RECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_RECORDActionPerformed
        // TODO add your handling code here:
         int a=Integer.parseInt(bid.getText());
        //if(yes.isSelected()==true){
        try{
           
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
            String y=(String)year.getSelectedItem();
            String m=(String)month.getSelectedItem();
            String d=(String)day.getSelectedItem();
            String s=""+y+"-"+m+"-"+d;
            
           // String y2=(String)year1.getSelectedItem();
            //String m2=(String)month2.getSelectedItem();
            //String d2=(String)day2.getSelectedItem();
            //String s2=""+y2+"-"+m2+"-"+d2;
            
            String x="";
            if(yes.isSelected()==true){
                x="YES";
                yes.setText(x);
       //  String query4="insert into addbook(book_id,book_name,author,category,issued,registration_no,name,issue_date) values('"+a+"','"+bname.getText()+"','"+author.getText()+"','"+category.getText()+"','"+x+"','"+prn.getText()+"','"+name.getText()+"','"+s+"');"; 
         
          String query4="insert into return_book(book_id,issued,registration_no,name,issue_date) values('"+a+"','"+x+"','"+prn.getText()+"','"+name.getText()+"','"+s+"');"; 
                     stmt.executeUpdate(query4);
            JOptionPane.showMessageDialog(null,"RECORD ADDED SUCCESSFULLY");
            System.out.println(query4);    
            bid.setText("");
        bname.setText("");
        author.setText("");
        category.setText("");
        prn.setText("");
        name.setText("");
        price.setText("");
        issued.setText("");
        issuedate.setText("");
        year.setSelectedIndex(0);
        month.setSelectedIndex(0);
        day.setSelectedIndex(0);
        year2.setSelectedIndex(0);
        month2.setSelectedIndex(0);
        day2.setSelectedIndex(0);
        buttonGroup1.clearSelection();    
        bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false);
            }
            }
        catch(Exception err){
            JOptionPane.showMessageDialog(null,"error");
        }
         
    }//GEN-LAST:event_ADD_RECORDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(bid.getText());
        //if(yes.isSelected()==true){
        try{
           
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
          /*  String y=(String)year.getSelectedItem();
            String m=(String)month.getSelectedItem();
            String d=(String)day.getSelectedItem();
            String s=""+y+"-"+m+"-"+d;
            */
           String y2=(String)year2.getSelectedItem();
           String m2=(String)month2.getSelectedItem();
           String d2=(String)day2.getSelectedItem();
           String s2=""+y2+"-"+m2+"-"+d2;
            
            String x="";
            if(no.isSelected()==true){
                x="NO";
                no.setText(x);
           // String query4="update addbook set issued='"+x+"',return_date='"+s2+"' where book_id="+a+";";        
           // String query4="update return_book set issued='"+x+"',return_date='"+s2+"' where book_id="+a+";";
            String query4="update return_book set issued='"+x+"',return_date='"+s2+"' where book_id="+a+" and registration_no="+prn.getText()+";";
           stmt.executeUpdate(query4);
            JOptionPane.showMessageDialog(null,"RECORD UPDATED SUCCESSFULLY");
            System.out.println(query4); 
            
            
            bid.setText("");
        bname.setText("");
        author.setText("");
        category.setText("");
        prn.setText("");
        name.setText("");
        price.setText("");
        issued.setText("");
        issuedate.setText("");
        year.setSelectedIndex(0);
        month.setSelectedIndex(0);
        day.setSelectedIndex(0);
        year2.setSelectedIndex(0);
        month2.setSelectedIndex(0);
        day2.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false); 
            }
            }
        catch(Exception err){
            JOptionPane.showMessageDialog(null,"error");
        }
         
    }//GEN-LAST:event_UPDATEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        bid.setText("");
        bname.setText("");
        author.setText("");
        category.setText("");
        prn.setText("");
        name.setText("");
        price.setText("");
        issued.setText("");
        issuedate.setText("");
        year.setSelectedIndex(0);
        month.setSelectedIndex(0);
        day.setSelectedIndex(0);
        year2.setSelectedIndex(0);
        month2.setSelectedIndex(0);
        day2.setSelectedIndex(0);
        buttonGroup1.clearSelection();
         bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false);
    }//GEN-LAST:event_CLEARActionPerformed

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        // TODO add your handling code here:
         new HOME().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_HOMEActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void ENABLE_EDIT_TO_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENABLE_EDIT_TO_ADDActionPerformed
        // TODO add your handling code here:
        bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(true);
        name.setEditable(false);
        year.setEnabled(true);
        month.setEnabled(true);
        day.setEnabled(true);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(true);
        no.setEnabled(false);
       
        
    }//GEN-LAST:event_ENABLE_EDIT_TO_ADDActionPerformed

    private void ENABLE_EDIT_TO_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENABLE_EDIT_TO_UPDATEActionPerformed
        // TODO add your handling code here:
        bname.setEditable(false);
        author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(true);
        month2.setEnabled(true);
        day2.setEnabled(true);
        yes.setEnabled(false);
        no.setEnabled(true);
    }//GEN-LAST:event_ENABLE_EDIT_TO_UPDATEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
int a=Integer.parseInt(bid.getText());
        try{
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
            
           // String query="select*from addbook where book_id="+a+";";
            //String query="select*from addbook,return_book where addbook.book_id=return_book.book_id and book_id="+a+";";
String query="select addbook.book_id,book_name,author,category,price,registration_no,name,issue_date,return_date"
       + ",issued from addbook,return_book where addbook.book_id=return_book.book_id and issued='yes' and addbook.book_id="+a+";";            
            System.out.println(query);
            ResultSet rs=stmt.executeQuery(query);
            System.out.println(query);
            String BNAME1,AUTHOR1,NAME,CATEGORY,ISSUED,BRANCH;
            
            String return_date,issue_date;
            int BID1,PRICE;
            long PRN,MOB;
            while(rs.next())
            
            {
                BID1=rs.getInt("book_id");
                PRICE=rs.getInt("price");
                BNAME1=rs.getString("book_name");
                AUTHOR1=rs.getString("author");
                PRN=rs.getLong("registration_no");
                NAME=rs.getString("name");
               // MOB=rs.getLong("mobile_no");
                 CATEGORY=rs.getString("category");
                 ISSUED=rs.getString("issued");
                 return_date=rs.getString("return_date");
                 issue_date=rs.getString("issue_date");
                 //BRANCH=rs.getString("branch");
               
              // model.addRow(new Object[]{BID1,BNAME1,AUTHOR1,CATEGORY,PRN,NAME,issue_date,return_date,ISSUED});
               bid.setText(Integer.toString(BID1));
                bname.setText(BNAME1);
                author.setText(AUTHOR1);
                issued.setText(ISSUED);
                issuedate.setText(issue_date);
                category.setText(CATEGORY);
                price.setText(Integer.toString(PRICE));
                prn.setText(Long.toString(PRN));
                //mob.setText(Long.toString(MOB));
                name.setText(NAME);
               // branch.setText(BRANCH);
                author.setEditable(false);
        category.setEditable(false);
        prn.setEditable(false);
        name.setEditable(false);
        price.setEditable(false);
     //   mob.setEditable(false);
       // branch.setEditable(false);
        year.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year2.setEnabled(false);
        month2.setEnabled(false);
        day2.setEnabled(false);
        yes.setEnabled(false);
        no.setEnabled(false); 
             
            }
            

        }
       catch(Exception err)
        {

            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                long p=Long.parseLong(prn.getText());
        try{
           
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/smartlib","root","root");
            Statement stmt=con.createStatement();
      
           // String query3="insert into return_book(book_id,book_name,author,category) values('"+bid.getText()+"','"+bname.getText()+"','"+author.getText()+"','"+category.getText()+"');";
            String query1="select registration_no,name from student where registration_no="+p+";";
   
            ResultSet rs=stmt.executeQuery(query1);
            String NAME,BRANCH;
            long PRN,MOB;
            while(rs.next()){
                PRN=rs.getLong("registration_no");
                NAME=rs.getString("name");
                //MOB=rs.getLong("mobile_no");
                //BRANCH=rs.getString("branch");
                    
            /*  {
                NO=rs.getString("issued");
                no.setSelected(true);
              }
                */

                prn.setText(Long.toString(PRN));
                name.setText(NAME);
               // mob.setText(Long.toString(MOB));
                //branch.setText(BRANCH);
            }

        }
        catch(Exception err){
            System.out.println(err.getMessage());
            JOptionPane.showMessageDialog(null,"error");
            
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISSUE_RECORD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISSUE_RECORD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISSUE_RECORD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISSUE_RECORD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISSUE_RECORD1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_RECORD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton ENABLE_EDIT_TO_ADD;
    private javax.swing.JButton ENABLE_EDIT_TO_UPDATE;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton HOME;
    private javax.swing.JButton SEARCH_BID;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField category;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> day2;
    private javax.swing.JTextField issued;
    private javax.swing.JTextField issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> month2;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField price;
    private javax.swing.JTextField prn;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JComboBox<String> year2;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
